{
 "title": "Kafka Client Fetch Analysis",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "topics",
    "query": "query_result(kafka_cluster_partition_replicascount{kubernetes_pod_name=~\"pipelines-strimzi-kafka-.\"})"
   },
   {
    "name": "apps",
    "query": "query_result(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_total{topic=~\"$topics\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Consumer Bytes Consumed Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_total{app=~\"$apps\",topic=~\"$topics\"}",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Consumer Records Consumed Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_consumed_total{app=~\"$apps\",topic=~\"$topics\"}",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Consumer Fetch Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_total{app=~\"$apps\"}",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Broker Fetch Request Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalfetchrequests_total{topic=~\"$topics\", kubernetes_pod_name=~\"pipelines-strimzi-kafka-.\"}[1m])) by (topic)",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Consumer Fetch Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_rate{app=~\"$apps\"}",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Broker Bytes Out Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesout_total{topic=~\"$topics\",kubernetes_pod_name=~\"pipelines-strimzi-kafka-.\"}[1m])) by (topic)",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Consumer Fetch Records Consumed Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_rate{app=~\"$apps\",topic=~\"$topics\"}[1m])",
     "legendFormat": "{{ app }}"
    }
   ]
  }
 ]
}